# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        symbol emergence: 10
        natural language processing: 10
        reinforcement learning: 10
        
        constructive learning: 5
        variational inference: 5
        robot: 5
        control: 5
        

# 通知の閾値
score_threshold: 10
